#!/bin/bash
# Saint Aveline - Smoke Test Checklist
# Run this after Phase 0 to verify game loop works

echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║           SAINT AVELINE - SMOKE TEST CHECKLIST                   ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "Open Unity and test each item manually. Mark [x] when verified."
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ PHASE 0 REQUIREMENTS (All must pass)                           │"
echo "├─────────────────────────────────────────────────────────────────┤"
echo "│ [ ] MENU:      Main Menu 'New Game' button loads Game scene    │"
echo "│ [ ] MOVE:      Player moves with WASD keys                     │"
echo "│ [ ] LOOK:      Player looks around with mouse                  │"
echo "│ [ ] INVENTORY: Press I to open inventory, equip weapon         │"
echo "│ [ ] SHOOT:     Left click fires equipped weapon                │"
echo "│ [ ] DAMAGE:    Enemy takes damage and dies when shot           │"
echo "│ [ ] HURT:      Player takes damage when enemy shoots           │"
echo "│ [ ] DEATH:     Player death shows GameOver scene               │"
echo "│ [ ] RETRY:     GameOver 'Retry' button restarts game           │"
echo "│ [ ] WIN:       Reaching roof trigger shows Victory screen      │"
echo "│ [ ] LOOP:      Victory/GameOver → Main Menu → New Game works   │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ PHASE 1 REQUIREMENTS (After parallel tracks merge)             │"
echo "├─────────────────────────────────────────────────────────────────┤"
echo "│ [ ] AMMO:      Weapon shows ammo count, reload with R          │"
echo "│ [ ] FEEDBACK:  Screen shakes when player takes damage          │"
echo "│ [ ] SON:       Son NPC follows when commanded                  │"
echo "│ [ ] DAUGHTER:  Daughter NPC follows when commanded             │"
echo "│ [ ] GRANDPA:   Grandfather NPC follows when commanded          │"
echo "│ [ ] AUDIO:     Background music plays, gunshots audible        │"
echo "│ [ ] AMBIENT:   Different areas have different ambient sounds   │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "┌─────────────────────────────────────────────────────────────────┐"
echo "│ MVP REQUIREMENTS (Final verification)                          │"
echo "├─────────────────────────────────────────────────────────────────┤"
echo "│ [ ] PLAYTHROUGH: Can complete game from start to victory       │"
echo "│ [ ] STABLE:      No crashes during 10 minute play session      │"
echo "│ [ ] PERFORMANCE: Maintains 60 FPS on mid-range hardware        │"
echo "│ [ ] FAMILY:      All family members respond to commands        │"
echo "│ [ ] COMBAT:      Combat feels responsive with feedback         │"
echo "└─────────────────────────────────────────────────────────────────┘"
echo ""
echo "Test Results:"
echo "  Date: $(date '+%Y-%m-%d %H:%M')"
echo "  Branch: $(git branch --show-current 2>/dev/null || echo 'unknown')"
echo "  Commit: $(git rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
echo ""
echo "If all Phase 0 items pass, reply: PHASE_0_COMPLETE"
echo "If all Phase 1 items pass, reply: PHASE_1_COMPLETE"
echo "If all MVP items pass, reply: MVP_COMPLETE"
